# Generated by Django 5.0.7 on 2024-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autentication',
            options={'verbose_name': 'اهراز هویت ', 'verbose_name_plural': 'اهراز هویت ها'},
        ),
        migrations.AlterField(
            model_name='autentication',
            name='image_pro',
            field=models.ImageField(blank=True, default='upload/profile/defult_pro.png', null=True, upload_to='upload/upload/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='autentication',
            name='verify_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
