# Generated by Django 5.0.7 on 2024-07-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_discription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100, verbose_name='عنوان')),
                ('discription_1', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('title_2', models.CharField(max_length=100, verbose_name='عنوان')),
                ('discription_2', models.TextField(verbose_name='توضیحات')),
                ('title_3', models.CharField(max_length=100, verbose_name='عنوان')),
                ('discription_3', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('title_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('title_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_5', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('title_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('title_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('title_8', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_8', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('title_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('title_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('discription_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'توضیح محصول',
                'verbose_name_plural': 'توضیجات محصولات',
            },
        ),
        migrations.CreateModel(
            name='product_men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80, verbose_name='نام محصول')),
                ('product_price', models.DecimalField(decimal_places=0, default=0.0, max_digits=20, verbose_name='قیمت محصول')),
                ('product_type', models.CharField(choices=[('simple', 'ساده'), ('discount', 'تخفیف'), ('new', 'جدبد')], default='S', max_length=10, verbose_name='مدل محصول')),
                ('price_discount', models.IntegerField(default=0, verbose_name='درصد تخفیف محصول')),
                ('product_image', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='product_shop', verbose_name='عکس محصول')),
                ('product_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ محصول')),
                ('product_visit', models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدید محصول')),
                ('product_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال بودن محصول')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('collect_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inheritance.collect_product', verbose_name='دسته بندی')),
                ('discription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.extra_discription', verbose_name='توضیحات محصول')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inheritance.brand', verbose_name='برند محصول')),
                ('tag_products', models.ManyToManyField(to='product_inheritance.tag_product', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'فروشگاه محصول',
                'verbose_name_plural': 'فروشگاه محصولات ',
            },
        ),
    ]
