# Generated by Django 5.0.7 on 2024-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_men',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/weblog_main/%Y/%m/%d', verbose_name='عکس محصول'),
        ),
    ]
