# Generated by Django 5.0.7 on 2024-07-27 10:42

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_men_product_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_men',
            name='product_discription',
            field=models.TextField(default=1, max_length=200, verbose_name='توضیحات اصلی محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_men',
            name='product_gender',
            field=models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'کودکانه')], default='men', max_length=10, verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_men',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
