# Generated by Django 5.0.7 on 2024-07-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_men_tag_products'),
        ('Product_details', '0003_rename_product_men_count_product_main_class_and_more'),
        ('favorite_prducts', '0026_alter_favorite_product_date'),
        ('product_inheritance', '0002_alter_collect_product_gender_and_more'),
        ('shopping_cart', '0002_alter_final_cart_code_tr_alter_finally_order_city_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_men',
            new_name='Product_main_class',
        ),
    ]
