# Generated by Django 5.0.7 on 2024-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل ')),
                ('subject', models.CharField(max_length=90, verbose_name='موضوع')),
                ('massege', models.TextField(verbose_name='پیغام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس  ها',
            },
        ),
        migrations.CreateModel(
            name='extra_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', models.TextField(verbose_name='توضیح حریم خصوصی ')),
                ('ruls_text', models.TextField(verbose_name='توضیح شرایط و قوانین ')),
            ],
            options={
                'verbose_name': 'تنظیم اضافه',
                'verbose_name_plural': 'تنظیمات اضافه',
            },
        ),
        migrations.CreateModel(
            name='sitesetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='ادرس شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شرکت')),
                ('phone', models.CharField(max_length=90, verbose_name='تلفن شرکت')),
                ('about_office', models.TextField(default='', verbose_name='درباره شرکت')),
                ('logo_image', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='logo', verbose_name='عکس لوگو')),
                ('instagrame_address', models.URLField(blank=True, null=True, verbose_name='ادرس اینستاگرام')),
                ('telegrame_address', models.URLField(blank=True, null=True, verbose_name='ادرس تلگرام ')),
                ('twitter_address', models.URLField(blank=True, null=True, verbose_name='ادرس تویتر')),
                ('write_ruls', models.TextField(default='', verbose_name='قوانین کپی رایت')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
