# Generated by Django 5.0.7 on 2024-07-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('product_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_pro', models.IntegerField(verbose_name='تعداد موجودی')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inheritance.color', verbose_name='رنگ انخابی انتخابی')),
                ('product_men', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product_men')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inheritance.size', verbose_name='سایز انتخابی')),
            ],
        ),
        migrations.CreateModel(
            name='product_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان محصول')),
                ('image', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='product_shop/product_gallery', verbose_name='عکس های محصول')),
                ('product_men', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product_men')),
            ],
            options={
                'verbose_name': 'گالری عکس',
                'verbose_name_plural': 'گالری عکس ها',
            },
        ),
    ]
