# Generated by Django 5.0.7 on 2024-07-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_details', '0002_alter_product_gallery_title_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='product_men',
            new_name='Product_main_class',
        ),
        migrations.RenameField(
            model_name='product_gallery',
            old_name='product_men',
            new_name='Product_main_class',
        ),
    ]
