# Generated by Django 5.0.7 on 2024-07-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0002_alter_final_cart_code_tr_alter_finally_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.BooleanField(default=False, verbose_name='ارسال شده / نشده')),
                ('factor', models.FileField(blank=True, null=True, upload_to='product_shop/factor', verbose_name='سند خرید pdf')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping_cart.final_cart', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'ارسال کردن محصول',
                'verbose_name_plural': 'ارسال کردن محصولات',
            },
        ),
    ]
