# Generated by Django 5.0.7 on 2024-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=90, verbose_name='متن کالکشن')),
                ('slider_image1', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن 1(560*380) ')),
                ('slider_image1_responsive', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن ریسپانسیو 1 (171*510)')),
                ('slider_image1_url', models.URLField(verbose_name='Url کالکشن 1 ')),
                ('slider_image2', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن 2 (265*515)')),
                ('slider_image2_responsive', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن ریسپانسیو 2  (171*510)')),
                ('slider_image2_url', models.URLField(verbose_name='Url کالکشن 2 ')),
                ('slider_image3', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن 3 (265*243)')),
                ('slider_image3_responsive', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن ریسپانسیو 3 (171*510)')),
                ('slider_image3_url', models.URLField(verbose_name='Url کالکشن 3 ')),
                ('slider_image4', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن 4 (265*790)')),
                ('slider_image4_responsive', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس کالکشن ریسپانسیو 4 (171*510)')),
                ('slider_image4_url', models.URLField(verbose_name='Url کالکشن 4 ')),
            ],
            options={
                'verbose_name': 'کالکشن',
                'verbose_name_plural': 'کالکشن ها ',
            },
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=90, verbose_name='متن اصلی اسلایدر')),
                ('about_title', models.CharField(max_length=90, verbose_name='توضیحات اسلایدر')),
                ('seasion_title', models.CharField(blank=True, max_length=90, null=True, verbose_name='متن دلخواه برای اسلایدر')),
                ('seasion_title_1', models.CharField(blank=True, max_length=90, null=True, verbose_name='متن دلخواه برای اسلایدر')),
                ('slider_image', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='slider', verbose_name='عکس اسلایدر ')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها ',
            },
        ),
    ]
