# Generated by Django 5.0.7 on 2024-07-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=50, verbose_name='برند محصول')),
                ('women', models.BooleanField(default=False, verbose_name='برند زنانه')),
                ('men', models.BooleanField(default=False, verbose_name='برند مردانه')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برند محصولات',
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=50, verbose_name='رنگ محصول')),
                ('product_color_english', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ محصول به انگلیسی')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ محصولات',
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=50, verbose_name='سایز محصول')),
                ('product_unit', models.CharField(max_length=50, verbose_name='واحد سایز')),
            ],
            options={
                'verbose_name': 'سایز محصول',
                'verbose_name_plural': 'سایز محصولات',
            },
        ),
        migrations.CreateModel(
            name='tag_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=20, verbose_name='نام تگ')),
                ('product_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تگ')),
                ('product_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال بودن تگ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'مدل تگ',
                'verbose_name_plural': 'مدل های تگ',
            },
        ),
        migrations.CreateModel(
            name='collect_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_collect_product_main', models.CharField(blank=True, max_length=80, verbose_name='عنوان دسته بندی')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنسیت')),
                ('name_collect_product_main', models.CharField(max_length=80, verbose_name='نام دسته بندی در url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_inheritance.collect_product', verbose_name='خانواده دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی  محصولات',
            },
        ),
    ]
