# Generated by Django 5.0.7 on 2024-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect_product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'کودکانه')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='collect_product',
            name='name_collect_product_main',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام دسته بندی در url'),
        ),
    ]
