# Generated by Django 5.0.7 on 2024-07-25 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0002_alter_product_men_product_image'),
        ('Product_details', '0002_alter_product_gallery_title_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pay', models.BooleanField(blank=True, default=False, null=True, verbose_name='پرداخت شده / نشده')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('code_tr', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد تایید')),
                ('Order_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='شماره سفارش')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'نهایی کردن سبد خرید',
                'verbose_name_plural': 'نهایی کردن سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت نهایی تکی محصول')),
                ('color_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_details.count', verbose_name='رنگ , سایز')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_men', verbose_name='محصول')),
                ('final_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.final_cart', verbose_name='سبدخرید')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': ' سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='finally_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='ادرس ')),
                ('post_code', models.CharField(max_length=90, verbose_name='کد پستی')),
                ('city', models.CharField(max_length=90, verbose_name='استان')),
                ('city_location', models.CharField(max_length=90, verbose_name='شهر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ادرس ارسال کردن',
                'verbose_name_plural': 'ادرس های ارسال کردن',
            },
        ),
    ]
