# Generated by Django 5.0.7 on 2024-07-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_cart',
            name='code_tr',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='کد تایید'),
        ),
        migrations.AlterField(
            model_name='finally_order',
            name='city',
            field=models.CharField(max_length=90, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='finally_order',
            name='city_location',
            field=models.CharField(max_length=90, verbose_name='استان'),
        ),
    ]
