# Generated by Django 5.0.7 on 2024-07-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_alter_final_cart_code_tr_alter_finally_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='درصد تخفیف نهایی تکی محصول'),
        ),
    ]
