# Generated by Django 5.0.7 on 2024-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_cart_final_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='finally_order',
            name='fullname',
            field=models.TextField(default='علیرضا', verbose_name='نام کامل '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finally_order',
            name='phone',
            field=models.TextField(default='09104554100', verbose_name='شماره'),
            preserve_default=False,
        ),
    ]
