# Generated by Django 5.0.7 on 2024-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_finally_order_fullname_finally_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='finally_order',
            name='factor_code',
            field=models.CharField(default='sasd', max_length=90, verbose_name='استان'),
            preserve_default=False,
        ),
    ]
