# Generated by Django 5.0.7 on 2024-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_finally_order_factor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finally_order',
            name='factor_code',
            field=models.CharField(max_length=90, verbose_name='کد سفارش'),
        ),
    ]
