# Generated by Django 5.0.7 on 2024-07-25 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_prducts', '0004_alter_favorite_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 9, 26, 57, 487893), verbose_name='تاریخ '),
        ),
    ]
