# Generated by Django 5.0.7 on 2024-07-27 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_prducts', '0009_alter_favorite_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 9, 1, 10, 286900), verbose_name='تاریخ '),
        ),
    ]
