# Generated by Django 5.0.7 on 2024-07-30 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_prducts', '0031_alter_favorite_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 18, 36, 41, 391861), verbose_name='تاریخ '),
        ),
    ]
